export type Internship = {
  slug: string;
  title: string;
  category: string;
  blurb: string;
  duration: string;
  location: string;
  start: string;
  looking: string[];
  responsibilities: string[];
  requirements: string[];
};

export const internships: Internship[] = [
  {
    slug: "equipment-engineering",
    title: "Equipment Engineering Intern",
    category: "Equipment — SAW",
    blurb:
      "Support BAW/SAW production ramp projects — tool setup, qualification and efficiency improvement projects alongside our equipment engineers.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["EEE / Mechatronics / Chemical", "Computer Science / Manufacturing", "Industrial or Systems Eng"],
    responsibilities: [
      "Support BAW/SAW production ramp projects in terms of tool setup and qualification.",
      "Set up PCI and documentation for tools.",
      "Work on improvement projects for low efficiency tools.",
      "Support engineers in equipment setup and improvement.",
      "Any ad-hoc tasks assigned by supervisor.",
    ],
    requirements: [
      "Pursuing a Bachelor's Degree in Electrical & Electronics, Mechatronics, Chemical, Computer Science, Manufacturing, Industrial or Systems Engineering.",
      "Team player with good leadership, communication and inter-personal skills.",
      "Engineering problem solving skills.",
      "Willingness to learn new skills and have initiative.",
    ],
  },
  {
    slug: "facilities-engineering",
    title: "Facilities Engineering Intern",
    category: "Facilities — Bedok",
    blurb:
      "Help monitor and maintain our plant water systems, analyse consumption data and work with contractors on preventive maintenance.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Electrical & Electronics Eng", "Mechanical Eng", "Reads technical drawings"],
    responsibilities: [
      "Assist in monitoring, operation and maintenance of water systems: RO/DI water, wastewater treatment, reclaim, glycerin and process cooling water.",
      "Assist engineers with data analysis and weekly/monthly water consumption reports.",
      "Assist the shift team in solving day-to-day operation and maintenance issues.",
      "Liaise with contractors on preventive maintenance, rectification and routine works.",
      "Submit incident reports on the above systems.",
      "Ensure system parameters are always kept within baseline.",
      "Build a fundamental understanding of other facilities systems such as ACMV.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in Electrical & Electronics Engineering or Mechanical Engineering.",
      "Able to evaluate technical drawings and schematics.",
      "Able to work as a team.",
    ],
  },
  {
    slug: "automation-camline",
    title: "Automation Intern (Camline)",
    category: "Automation",
    blurb:
      "Troubleshoot and enhance our Camline manufacturing systems with production, engineering, IT and QA teams, and support automation projects.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["EEE / Mechatronics / Chemical", "Computer Science / Manufacturing", "Industrial or Systems Eng"],
    responsibilities: [
      "Work closely with production, engineering (process & equipment), IT and QA to investigate, troubleshoot and resolve Camline issues raised.",
      "Engage production, engineering teams and external solution providers to implement automation projects and hit implementation targets/KPIs.",
      "Participate in Skyworks automation Camline projects for productivity and quality improvement.",
      "Provide support to the automation team for investigation and enhancement activity.",
      "Any other ad-hoc duties as assigned.",
    ],
    requirements: [
      "Pursuing a Bachelor's Degree in Electrical & Electronics, Mechatronics, Chemical, Computer Science, Manufacturing, Industrial or Systems Engineering.",
      "Fast learner for new systems with minimum supervision.",
      "Good communication and documentation skills.",
      "Strong and systematic problem solving and troubleshooting skills.",
      "Good team player, able to work independently, with a passion for continuous learning.",
      "Preferred: project handling experience, basic machine operational knowledge, flow charting, exposure to robotics, AI and machine learning.",
    ],
  },
  {
    slug: "capex-sourcing",
    title: "CAPEX Sourcing Intern",
    category: "Sourcing & Procurement",
    blurb:
      "Support procurement of long-term assets — RFQs, supplier quotation analysis, spend analysis and cost optimisation with engineering teams.",
    duration: "6 months",
    location: "Singapore",
    start: "Flexible",
    looking: ["Supply Chain / Logistics", "Business or Operations", "Industrial or Systems Eng"],
    responsibilities: [
      "Support procurement teams in acquiring long-term assets such as machinery, equipment and infrastructure.",
      "Prepare RFQs, analyse supplier quotations and track performance metrics.",
      "Assist with contract negotiation, maintain documentation and conduct market research.",
      "Collaborate with engineering teams to optimise cost and delivery.",
      "Any ad-hoc tasks as requested.",
    ],
    requirements: [
      "Currently pursuing or recently completed a Diploma or Bachelor's Degree in Supply Chain Management, Logistics & Transportation, Business Administration or Management, Industrial or Systems Engineering, Operations Management, or Procurement / Strategic Sourcing.",
      "A minimum GPA of 3.0 may be preferred.",
      "Proficiency in Microsoft Excel, including Pivot Tables, VLOOKUP and basic data visualisation.",
      "Exposure to SAP and Power BI is highly advantageous; familiarity with Ariba or other digital procurement platforms is a plus.",
      "Strong data cleaning and analysis skills to support spend analysis and supplier performance tracking.",
    ],
  },
  {
    slug: "data-scientist",
    title: "Data Scientist Intern",
    category: "Global Sourcing",
    blurb:
      "Build proof-of-concept data models for our Global Sourcing team — new databases, algorithms and predictive models, then share the insights.",
    duration: "6 months",
    location: "Ang Mo Kio, Singapore",
    start: "Flexible",
    looking: ["Data Science / Analytics", "Manufacturing / Industrial / Systems Eng", "Business"],
    responsibilities: [
      "Work closely with Skyworks Global Sourcing stakeholders to understand their business goals.",
      "Determine the best data sources and models to support those goals.",
      "Engage cross-functional stakeholders from finance, business lines and external consultants.",
      "Develop proof-of-concept data models, including new databases, creative algorithms and predictive models.",
      "Present data creatively and share insights with team members.",
      "Integrate POC models into existing business processes.",
    ],
    requirements: [
      "Undergraduate degree in Manufacturing, Industrial or Systems Engineering, Business, Data Science and/or Business Analytics.",
      "Experience with MS Excel and artificial intelligence.",
    ],
  },
  {
    slug: "factory-automation-hardware",
    title: "Factory Automation (Hardware) Intern",
    category: "Factory Automation",
    blurb:
      "Implement automation systems on the production floor — in-house, customised and off-the-shelf solutions — and help qualify new projects with our engineering teams.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Any Engineering discipline", "Computer Science", "Project experience"],
    responsibilities: [
      "Participate in Skyworks automation projects for productivity and quality improvement.",
      "Implement automation systems comprising in-house developed, customised solutions and off-the-shelf products on the production floor.",
      "Work closely with production, engineering (process & equipment) and IT to troubleshoot and resolve production systems issues.",
      "Work with engineering and external solution providers to introduce and qualify automation projects that improve quality control and operational flow.",
      "Identify system enhancement opportunities, propose improvement plans and implement them in the production environment.",
      "Prepare project proposals for review and CAPEX submission where necessary.",
      "Support the engineering team with project implementation and drive day-to-day adoption of systems.",
      "Create and document best practices on using automation systems for end users.",
      "Any other ad-hoc duties as assigned.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in any Engineering or Computer Science discipline.",
      "Experience with handling projects (e.g. event organising).",
      "Fast learner for new systems with minimum supervision, with a passion for continuous learning.",
      "Good communication and documentation skills.",
      "Strong and systematic problem solving and troubleshooting skills.",
      "Good team player, able to work independently.",
    ],
  },
  {
    slug: "factory-automation-software",
    title: "Factory Automation (Software) Intern",
    category: "Factory Automation",
    blurb:
      "Apply AI to image analysis and defect detection on the WLT AI Image Judgment project, and build scripts that automate manual production tasks.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Computer Science / EEE", "Automation / Mechatronics", "Python or C++, AI/ML"],
    responsibilities: [
      "Support the WLT AI Image Judgment project, applying AI techniques to enhance image analysis and defect detection.",
      "Assist in the development and deployment of automation solutions across production lines.",
      "Collaborate with production, process & equipment engineering, IT and QA to identify and implement automation opportunities.",
      "Write, test and maintain scripts and programs to automate manual tasks and improve operational efficiency.",
      "Participate in data collection, preprocessing and analysis to support AI model training and validation.",
      "Document project progress and technical findings, and present results to stakeholders.",
      "Contribute to continuous improvement initiatives and explore emerging technologies in AI and automation.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's or Master's degree in Computer Science, Electrical Engineering, Automation, Mechatronics or a related field.",
      "Strong programming skills in Python, C++ or similar languages.",
      "Hands-on experience with AI/ML projects, preferably involving image processing or computer vision.",
      "Excellent communication and interpersonal skills.",
      "Team player with a proactive attitude and strong problem-solving abilities.",
      "Passion for continuous learning and innovation, able to work independently and manage multiple tasks.",
    ],
  },
  {
    slug: "ic-layout-design",
    title: "IC Layout Design Intern",
    category: "MSB Layout",
    blurb:
      "Simulate and validate integrated circuits used in mobile phones, correlating measurements with simulations across supply, temperature and process variations.",
    duration: "6 months",
    location: "Ang Mo Kio, Singapore",
    start: "Flexible",
    looking: ["Any Engineering discipline", "RF / Analog IC interest", "Cadence, ADS, Spice, MatLab"],
    responsibilities: [
      "Simulate and validate performance of integrated circuits for mobile phones across supply, temperature and process variations.",
      "Extensive transistor and passive-device design and simulation to understand circuit kernels, correlating measurements with simulations.",
      "Create compliance matrices against spec, analyse and plot data, and present results to a larger audience.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in any Engineering discipline.",
      "Strong interest and understanding in RF/Analog IC design.",
      "Knowledge of semiconductor devices; physics or electromagnetism is a plus.",
      "Exposure to EDA tools such as Cadence, ADS, Spice or MatLab is a major plus.",
      "Self-motivated team player with a strong desire to keep learning on the job.",
    ],
  },
  {
    slug: "industrial-engineering",
    title: "Industrial Engineering Intern",
    category: "Industrial Engineering — BAW",
    blurb:
      "Run time and motion studies on the shopfloor, support continuous improvement projects and build dashboards that track OEE and productivity.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Industrial / Systems Eng", "Manufacturing Eng", "Python, VBA, Power BI, SQL"],
    responsibilities: [
      "Identify and analyse operational waste and support Continuous Improvement Program (CIP) initiatives through automation, process optimisation and work method reviews.",
      "Perform on-site observation and time and motion studies on the production shopfloor to support productivity and capacity analysis.",
      "Assist industrial engineers in collecting, analysing and validating operational data for improvement projects.",
      "Support preparation, maintenance and version control of IE documentation (process flows, SOPs, time study records, layouts).",
      "Participate in OEE tracking, CIP implementation and performance improvement activities.",
      "Support data visualisation and reporting for IE projects (dashboards, trend analysis, KPI tracking).",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in Industrial Engineering, Systems Engineering, Manufacturing Engineering or a related discipline.",
      "Good working knowledge of Microsoft Excel, PowerPoint and Word (data analysis, charting, presentation).",
      "Hands-on experience in coding, application development and dashboard reporting (Python, VBA, Power BI, Tableau, SQL or similar).",
      "Basic understanding of manufacturing or production processes is an advantage.",
      "Ability to observe processes critically and apply data-driven problem solving.",
      "Strong analytical, communication and documentation skills.",
      "Proactive, willing to learn and comfortable working on the production shopfloor.",
    ],
  },
  {
    slug: "manufacturing",
    title: "Manufacturing Intern",
    category: "Manufacturing",
    blurb:
      "Build Power BI dashboards and reports for manufacturing stakeholders, working with SQL databases to turn production data into decisions.",
    duration: "6 months",
    location: "Singapore",
    start: "Flexible",
    looking: ["Power BI & SQL", "Data analysis", "Detail-oriented"],
    responsibilities: [
      "Design, develop and maintain project solutions using Power BI.",
      "Create dashboards, reports and data visualisations to help stakeholders make data-driven decisions.",
      "Work with SQL databases and Excel to extract and manipulate data.",
      "Collaborate with project users to understand reporting needs and translate them into technical requirements.",
      "Optimise and improve existing Power BI reports and data models.",
      "Conduct data analysis, provide insights and recommendations, and ensure data accuracy and integrity across all reports and dashboards.",
    ],
    requirements: [
      "Ability to analyse and visualise data effectively.",
      "Excellent problem-solving and analytical skills.",
      "Proficiency in SQL, with understanding and experience of database management.",
      "Ability to work with large datasets and perform data cleansing.",
      "Detail-oriented with a strong commitment to data accuracy.",
    ],
  },
  {
    slug: "npi-engineering",
    title: "NPI Engineering Intern",
    category: "Filter NPI",
    blurb:
      "Coordinate engineering sample builds with stakeholders, track on-time delivery and support new part introduction with yield and defect analysis.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Any Engineering discipline", "Project coordination", "Yield & defect analysis"],
    responsibilities: [
      "Plan and liaise with stakeholders on the delivery of engineering samples.",
      "Track and ensure On-Time Delivery (OTD) of engineering samples to meet customer demand.",
      "Highlight issues found and follow up with a mitigation plan.",
      "Support project managers in meetings and conferences by organising meetings and taking minutes.",
      "Support new part introduction.",
      "Yield compilation and analysis.",
      "Defect analysis for low yield lots and wafers.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in any Engineering discipline.",
      "Understand the whole process of the production line from setup to final test independently.",
      "Comfortable with cross-functional interaction and integration across departments.",
      "Apply basic project management skills in a cross-functional / cross-cultural environment.",
      "Keen to pick up planning skills in a dynamic high-volume manufacturing environment.",
    ],
  },
  {
    slug: "planning",
    title: "Planning Intern",
    category: "Planning",
    blurb:
      "Assist with customer demand planning, production schedules and KPI reporting, and contribute ideas for planning process improvements.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Industrial / Manufacturing Eng", "Operations or Supply Chain", "Excel, Power BI, SAP a plus"],
    responsibilities: [
      "Assist in customer demand planning, commitment and inventory management.",
      "Assist in the development of production schedules and planning improvement projects.",
      "Participate in data analysis to identify trends, improvement opportunities and potential production issues.",
      "Support the tracking and reporting of production metrics and key performance indicators (KPIs).",
      "Contribute ideas for process enhancement and efficiency.",
    ],
    requirements: [
      "Currently pursuing a degree in Industrial Engineering, Manufacturing Engineering, Operations Management, Supply Chain Management or a related field.",
      "Familiarity with production processes and planning concepts is preferred.",
      "Proficient in Microsoft Office (Excel, Word, PowerPoint).",
      "Experience with Power BI, SAP and scheduling systems is a plus.",
      "Strong analytical skills and attention to detail.",
      "Able to work in a fast-paced environment, willing to learn and adapt to new challenges.",
    ],
  },
  {
    slug: "sharepoint-website-development",
    title: "SharePoint Website Development Intern",
    category: "BAW Development",
    blurb:
      "Design, build and maintain internal SharePoint sites and web parts, from requirements gathering through testing and troubleshooting.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["Computer Science / IT", "HTML, CSS, JavaScript", "SharePoint a plus"],
    responsibilities: [
      "Independently research and learn how to design, develop and maintain websites using Microsoft SharePoint.",
      "Collaborate with a senior team member to gather and define requirements.",
      "Create and customise SharePoint sites, pages and web parts.",
      "Implement and test new features and functionalities.",
      "Troubleshoot and resolve issues related to SharePoint sites.",
      "Ensure websites are optimised for performance and usability.",
      "Participate in code reviews and provide constructive feedback.",
      "Stay updated with the latest trends and best practices in web development and SharePoint.",
    ],
    requirements: [
      "Currently pursuing a degree in Computer Science, Information Technology or a related field.",
      "Basic understanding of web development technologies (HTML, CSS, JavaScript).",
      "Familiarity with Microsoft SharePoint is a plus.",
      "Strong problem-solving skills and attention to detail.",
      "Excellent communication and teamwork abilities.",
      "Eagerness to learn and adapt to new technologies.",
    ],
  },
  {
    slug: "sourcing",
    title: "Sourcing Intern",
    category: "Sourcing",
    blurb:
      "Turn sourcing data into interactive dashboards, automate manual reports and support alternate vendor and material sourcing for cost savings.",
    duration: "6 months",
    location: "Singapore",
    start: "Flexible",
    looking: ["Supply Chain & Logistics", "Business Analytics / Engineering", "Excel, Power BI, VBA"],
    responsibilities: [
      "Extract and transform data, ensuring data quality.",
      "Create informative, interactive dashboards for business decision-making.",
      "Develop and maintain dashboard infrastructures.",
      "Source alternate vendors and/or materials to achieve cost savings or upon request.",
      "Identify areas for improvement in daily reports to enhance productivity.",
      "Create forms to solicit internal or external feedback.",
      "Transfer current manual reports to automated forms (e.g. Power BI, VBA).",
      "Any ad-hoc tasks as requested.",
    ],
    requirements: [
      "Pursuing a Bachelor's Degree in Supply Chain & Logistics, Business Analytics or Engineering.",
      "Experience with data analytics tools (e.g. Excel, Power BI).",
      "Familiarity with digital enhancements and automation using Microsoft tools (Excel VBA, Power Query, Power Automate).",
      "Knowledge of SQL is an added advantage.",
      "Strong attention to detail and good organisational skills.",
    ],
  },
  {
    slug: "supply-chain",
    title: "Supply Chain Intern",
    category: "TMG Singapore Supply Chain",
    blurb:
      "Analyse supply and demand data, maintain reporting and support our planners with Power BI report activities.",
    duration: "6 months",
    location: "Ang Mo Kio, Singapore",
    start: "Flexible",
    looking: ["Supply Chain / Operations", "Any Engineering discipline", "Excel & Power BI"],
    responsibilities: [
      "Supply and demand data analysis.",
      "Maintenance and regular updating of reports.",
      "Coordination and data gathering for report generation.",
      "Support the team with Power BI report activities.",
      "Support the team with tasks assigned by planners.",
      "Any ad-hoc tasks as assigned.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in Supply Chain, Operations or any Engineering related discipline.",
      "Good working knowledge of Microsoft Office (Excel, Word, PowerPoint) is required.",
      "Good working knowledge of Power BI is a plus.",
      "Other software and planning system knowledge is good to have.",
    ],
  },
  {
    slug: "talent-acquisition",
    title: "Talent Acquisition Intern",
    category: "Human Resources",
    blurb:
      "Work on employer branding, campus recruitment and talent acquisition process improvement with our HR team.",
    duration: "6 months",
    location: "Ang Mo Kio, Singapore",
    start: "Flexible",
    looking: ["Business Admin / HR / Marketing", "Strong communicator", "Detail-oriented"],
    responsibilities: [
      "Employer branding: evaluate our current position and suggest improvements; support the local Tripartite Standards of Recruitment Practices project.",
      "Campus recruitment: organise university site tours of our manufacturing plant and participate in campus recruitment fairs.",
      "Consolidate campus events from different schools and support internship administration.",
      "Contribute to process improvements in the TA workflow, aligned across HR functions, and review how recruitment metrics are compiled.",
      "Support early talent identification and pipelining — analyse, plan, recruit, hire, onboard and convert top intern talent.",
      "Support strategic talent-mapping and market research projects, delivering insights to business leaders.",
      "Partner with HR business partners and leaders on engagement and hiring programmes for interns and graduates.",
      "Engage with the global recruiting and university relations community on successful methodologies.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree or Diploma in Business Administration, HR or Marketing.",
      "Detail-oriented and proficient in MS Office.",
      "Inquisitive mind with strong communication, coordination and follow-up skills.",
      "Strong team player, comfortable with multi-cultural and cross-functional teams.",
      "Able to manage stakeholders at all levels and handle recruitment documentation.",
      "Self-driven, takes initiative and able to work independently.",
    ],
  },
  {
    slug: "visual-inspection-process-engineering",
    title: "Visual Inspection Process Engineering Intern",
    category: "DPS — SAW",
    blurb:
      "Monitor automated visual inspection and daily yield loss, automate the process database and drive process improvement projects.",
    duration: "6 months",
    location: "Chai Chee, Singapore",
    start: "Flexible",
    looking: ["Any Engineering discipline", "Excel Macro / Python / SQL", "Power BI data analysis"],
    responsibilities: [
      "Automated visual inspection, line maintenance and daily yield loss monitoring for overkill or other quality-related issues.",
      "Carry out and improve automation of the process database.",
      "Carry out process improvement tasks or projects delegated by the engineer or supervisor.",
      "Support Engineering Abnormal Reports, Non-Conformance Reviews, Special Test Requests and follow-up activities.",
      "Any ad-hoc tasks assigned by supervisor.",
    ],
    requirements: [
      "Pursuing a Bachelor's Degree or Diploma in any Engineering discipline.",
      "Team player with good leadership, communication and inter-personal skills.",
      "Engineering problem solving skills.",
      "Willingness to learn new skills and have initiative.",
      "Knowledge of Excel Macro / Python, Visual Studio Code and SQL.",
      "Data analysis using Power BI and Excel.",
    ],
  },
  {
    slug: "yield-engineering-baw-saw",
    title: "Yield Engineering (BAW/SAW) Intern",
    category: "Yield — SAW",
    blurb:
      "Analyse high-volume manufacturing data and contribute to yield improvement initiatives across our SAW and BAW filter technologies.",
    duration: "6 months",
    location: "Bedok, Singapore",
    start: "Flexible",
    looking: ["EEE / Mechatronics / Chemical", "Computer or Data Science", "Power BI & SQL"],
    responsibilities: [
      "Analyse high-volume manufacturing data across multiple product lines.",
      "Contribute to yield improvement initiatives for SAW and BAW technologies.",
      "Monitor and analyse key processes such as Back-End Yield, Final Inspection and Visual Inspection.",
      "Support RMA and defect root cause investigations.",
      "Assist in rework and maverick lot improvement analysis.",
      "Present findings in a structured and data-driven manner.",
      "Understand and perform big data analysis.",
      "Work on yield improvement projects for BAW.",
    ],
    requirements: [
      "Currently pursuing a Bachelor's Degree in Electrical & Electronics, Mechatronics, Computer Science / Data Science, Manufacturing, Industrial, Chemical or Systems Engineering.",
      "Strong analytical and critical thinking skills.",
      "Familiarity with Power BI, SQL or any data analysis tools.",
      "Good communication and teamwork skills.",
    ],
  },
];


